from tortoise import fields
from tortoise.models import Model

class MDBMPPurchaseRecord(Model):
    id = fields.CharField(max_length=64, pk=True, description='主键')
    source = fields.CharField(max_length=255, null=True, description='来源')
    type = fields.CharField(max_length=255, null=True, description='类别')
    no = fields.CharField(max_length=1023, null=True, description='卡号')
    par_value = fields.DecimalField(max_digits=10, decimal_places=3, null=True, description='面值')
    rate = fields.DecimalField(max_digits=10, decimal_places=3, null=True, description='汇率')
    total_price = fields.DecimalField(max_digits=19, decimal_places=3, null=True, description='总价值')
    purchaser_no = fields.CharField(max_length=255, null=True, description='采购员编号')
    purchaser_name = fields.CharField(max_length=255, null=True, description='采购员')
    purchase_time = fields.DatetimeField(null=True, description='采购时间')
    supplier_id = fields.CharField(max_length=64, null=True, description='供应商ID')
    supplier_name = fields.CharField(max_length=255, null=True, description='供应商')
    sales_flag = fields.CharField(max_length=2, null=True, description='是否已售')
    sales_id = fields.CharField(max_length=64, null=True, description='出售记录ID')
    alarm_flag = fields.CharField(max_length=8, null=True, description='告警标记')
    alarm_code = fields.CharField(max_length=32, null=True, description='告警码')
    msg_base64 = fields.CharField(max_length=1023, null=True, description='消息识别码')
    from_wxid = fields.CharField(max_length=64, null=True, description='消息来源ID')
    robot_wxid = fields.CharField(max_length=64, null=True, description='机器人ID')
    order_num = fields.CharField(max_length=8, null=True, description='排序号')
    create_user_id = fields.CharField(max_length=64, null=True, description='创建人ID')
    create_user_name = fields.CharField(max_length=255, null=True, description='创建人Name')
    create_time = fields.DatetimeField(null=True, description='创建时间')
    update_user_id = fields.CharField(max_length=64, null=True, description='更新人ID')
    update_user_name = fields.CharField(max_length=255, null=True, description='更新人Name')
    update_time = fields.DatetimeField(null=True, description='更新时间')
    usable = fields.CharField(max_length=8, null=True, description='是否可用：0-禁用，1-可用')
    del_flag = fields.CharField(max_length=8, null=True, description='删除标记：0-删除，1-正常')
    purchaser_id = fields.CharField(max_length=255, null=True)
    purchaser_name_abbr = fields.CharField(max_length=255, null=True)
    dept_id = fields.CharField(max_length=64, null=True)
    dept_name = fields.CharField(max_length=255, null=True)
    adjustment_detail = fields.CharField(max_length=255, null=True)
    adjustment_flag = fields.CharField(max_length=8, null=True)
    adjustment_id = fields.CharField(max_length=64, null=True)
    adjustment_type = fields.CharField(max_length=32, null=True)
    alarm_content = fields.CharField(max_length=255, null=True)
    detail = fields.CharField(max_length=255, null=True)
    profit = fields.DecimalField(max_digits=10, decimal_places=3, null=True)
    remaining_amount = fields.DecimalField(max_digits=10, decimal_places=3, null=True)
    remaining_amount_operate = fields.DecimalField(max_digits=10, decimal_places=3, null=True)
    stock = fields.DecimalField(max_digits=10, decimal_places=3, null=True)
    stock_operate = fields.DecimalField(max_digits=10, decimal_places=3, null=True)

    class Meta:
        table = "md_bmp_purchase_record"
        table_description = "采购记录表"
